### ISSUE TITLE
Question for the VDB

### ISSUE THREAD

**Issue by SCUTykLin** [wolfball/PlenVDB#5]
Great paper.
And I have a question, VDB has four layers, How do you know where to split the VDB?

For example, we know a voxel have something, How to decide if he's going to keep splitting down to the leefnode or if it's an internal node.

Thanks

**Comment by wolfball** [comment]
Thanks for your attention!

You can understand the VDB establishment process as bottom-up: first you split the whole space (e.g. $[-1, 1]^3$) into $N^3$ voxels which is the smallest elements, and then every $8^3$ voxels form a LeafNode, every $16^3$ LeafNodes form a InternalNode, every $32^3$ InternalNodes form a RootNode.

So, a voxel can not be split down to smaller elements, and when a VDB tree is established, the type of all Nodes (aggregations of voxels, e.g. LeafNode, InternalNode) are also defined.

If I misunderstand your questions, plz let me know.

**Comment by SCUTykLin** [comment]
Oh, I see, u train a nerf firstly, and convert the nerf into VDB, right?

**Comment by wolfball** [comment]
> Oh, I see, u train a nerf firstly, and convert the nerf into VDB, right?

That is an solution. But here we actually directly optimize the parameters stored in VDBs without additional conversion process. And this is achieved through the additionally encapsulated functions in https://github.com/wolfball/PlenVDB/tree/main/plenvdb/lib/vdb.

**Comment by SCUTykLin** [comment]
Ok, the structure of the VDB is determined when train DVGO firstly. Then u train the parameters of the VDB secondly. right?

**Comment by wolfball** [comment]
> Ok, the structure of the VDB is determined when train DVGO firstly. Then u train the parameters of the VDB secondly. right?

I think there is no "firstly" or "secondly" here. DVGO is a method that directly optimizes parameters stored in a 3D grid, while  ours directly optimizes parameters stored in VDBs. The only difference lies in the data structure (3D grid v.s. VDB).

**Comment by SCUTykLin** [comment]
Thanks for your reply, I understand.
